[package]
name = "rollit"
version = "3.1.2"
edition = "2021"

[dependencies]
gtk-macros = "0.3.0"
once_cell = "1.17.1"
log = "0.4.17"
pretty_env_logger = "0.5.0"
random-number = "0.1.8"
regex = "1.7.3"

[dependencies.gtk]
package = "gtk4"
version = "0.6.6"
features = ["gnome_44"]

[dependencies.gio]
package = "gio"
version = "0.17.4"
features = ["v2_76"]


[dependencies.adw]
package = "libadwaita"
version = "0.4.1"
features = ["v1_3"]

[dependencies.gettext-rs]
version = "0.7.0"
features = ["gettext-system"]
