[package]
name = "rollit"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk-macros = "0.3.0"
pretty_env_logger = "0.4.0"
random-number = "0.1.7"
regex = "1.6.0"

[dependencies.gtk]
package = "gtk4"
version = "0.4.4"
features = ["v4_6"]

[dependencies.gio]
package = "gio"
version = "0.15.2"
features = ["v2_70"]


[dependencies.adw]
package = "libadwaita"
version = "0.2.0-alpha.2"
features = ["v1_2"]

[dependencies.gettext-rs]
version = "0.7.0"
features = ["gettext-system"]
